spring.application.name=DCBA
spring.profiles.active=prod
spring.jpa.defer-datasource-initialization=true
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
management.endpoints.web.exposure.include=prometheus,health,info
management.metrics.tags.application=${spring.application.name}
